[project]
name = "miniproject1jacehesford"
version = "0.1.0"
description = "A project to take api finance data and create graphs in the format of pngs."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "yfinance>=1.1.0",
]
